#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 15 03:08:07 2018

@author: tys
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 12 02:35:14 2018

@author: tys
"""


from migen import *
from migen.build.platforms import vip_board
from migen.fhdl.verilog import convert
 
class Adder(Module):
    def __init__(self, width = 4):
        
        a = Signal(width)
        b = Signal(width)
        c = Signal(width)
        carry = Signal()
        
        e = Signal(width+1)  
        
        
        self.sync += e.eq(a+b), c.eq(e[0:width])
        self.sync += If( e>2,
                           carry.eq(e[width])
                      ).Else(
                            carry.eq(0)
                      )
        
        
        
        
dut = Adder(32);

print(convert(dut, name = 'adder3bit') )
